# Generated by Django 3.2 on 2021-06-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hiddeninfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('mobile_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='personal',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
