# Generated by Django 3.2 on 2021-06-01 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0002_auto_20210601_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='resume_app.basic_info'),
        ),
    ]
