# Generated by Django 3.2 on 2021-06-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0003_alter_personal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
