# Generated by Django 3.2 on 2021-06-01 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0004_alter_personal_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hiddeninfo',
        ),
        migrations.DeleteModel(
            name='rlogin',
        ),
    ]
