# Generated by Django 3.2 on 2021-06-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0005_auto_20210602_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='dummy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=5)),
                ('Address_line1', models.CharField(max_length=100)),
                ('Address_line2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='post_info',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('post_type', models.CharField(max_length=20)),
                ('post', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=30)),
            ],
        ),
    ]
