# Generated by Django 3.2 on 2021-06-02 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0006_dummy_post_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dummy',
        ),
    ]
