# Generated by Django 3.2 on 2021-06-02 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0008_dummy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dummy',
            new_name='dummy1',
        ),
    ]
