# Generated by Django 3.2 on 2021-06-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0009_rename_dummy_dummy1'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidate_info',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('phno', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=5)),
                ('Add1', models.CharField(max_length=100)),
                ('Add2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=50)),
                ('pType', models.CharField(max_length=20)),
                ('desig', models.CharField(max_length=20)),
                ('dept', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='basic_info',
        ),
        migrations.DeleteModel(
            name='dummy1',
        ),
        migrations.DeleteModel(
            name='personal',
        ),
        migrations.DeleteModel(
            name='post_info',
        ),
    ]
