# Generated by Django 3.2 on 2021-06-09 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0013_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='uploaded_at',
        ),
    ]
