# Generated by Django 3.2 on 2021-06-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0014_remove_document_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_info',
            name='document',
            field=models.FileField(default='EMPTY', upload_to='documents/'),
        ),
    ]
