# Generated by Django 3.2 on 2021-06-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0015_candidate_info_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_info',
            name='document',
            field=models.FileField(default='', upload_to='documents/'),
        ),
    ]
