# Generated by Django 3.2 on 2021-06-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0016_alter_candidate_info_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_info',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='candidate_info',
            name='Add1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate_info',
            name='Add2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate_info',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate_info',
            name='dept',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='candidate_info',
            name='desig',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidate_info',
            name='gender',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='candidate_info',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidate_info',
            name='pType',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidate_info',
            name='phno',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='candidate_info',
            name='pin',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate_info',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
    ]
