# Generated by Django 3.2 on 2021-06-10 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0017_auto_20210610_1029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.RemoveField(
            model_name='candidate_info',
            name='document',
        ),
        migrations.RemoveField(
            model_name='candidate_info',
            name='image',
        ),
    ]
