# Generated by Django 3.2 on 2021-06-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0019_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='email',
        ),
        migrations.RemoveField(
            model_name='document',
            name='id',
        ),
        migrations.AddField(
            model_name='document',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='document',
            name='phno',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(default='', upload_to='documents/'),
        ),
    ]
