# Generated by Django 3.2 on 2021-06-14 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0020_auto_20210610_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='phno',
            new_name='Phone_number',
        ),
    ]
