# Generated by Django 3.2 on 2021-07-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0025_remove_technical_info_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='technical_info',
            name='interest',
            field=models.CharField(default='', max_length=500),
        ),
    ]
